### ISSUE TITLE
Python can't find installed PyKDL

### ISSUE THREAD

**Issue by mr3albert** [collaborative-robotics/surgical_robotics_challenge#16]
I'm trying to run the example gui controller to move the simulator robot arms. 
I could not get my python to find PyKDL. I am using anaconda python.
```
Traceback (most recent call last):
  File "gui_based_control.py", line 45, in <module>
    from surgical_robotics_challenge.kinematics.psmIK import *
  File "/home/mr3albert/Documents/UCSD/SRIP_UCSD/surgical_robotics_challenge/scripts/surgical_robotics_challenge/kinematics/psmIK.py", line 46, in <module>
    from PyKDL import Vector, Rotation, Frame, dot
ModuleNotFoundError: No module named 'PyKDL'
```

I have already installed PyKDL using `sudo apt install python3-PyKDL`
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3-pykdl is already the newest version (1.4.0-7ubuntu1).
The following packages were automatically installed and are no longer required:
  libassimp-dev libassimp5 libcurl4-openssl-dev libeigen3-dev libfreeimage3 libjxr0 libogre-1.9-dev
  libogre-1.9.0v5 liborocos-kdl-dev libtinyxml-dev libtinyxml2.6.2v5 liburdfdom-dev
  liburdfdom-headers-dev liburdfdom-model liburdfdom-model-state liburdfdom-sensor liburdfdom-world
  libzzip-0-13 linux-headers-5.4.0-91 linux-headers-5.4.0-91-generic linux-image-5.4.0-91-generic
  linux-modules-5.4.0-91-generic linux-modules-extra-5.4.0-91-generic ros-noetic-angles
  ros-noetic-laser-geometry ros-noetic-map-msgs ros-noetic-media-export ros-noetic-nav-msgs
  ros-noetic-resource-retriever ros-noetic-rosconsole-bridge ros-noetic-roswtf ros-noetic-tf
  ros-noetic-turtle-tf ros-noetic-urdf ros-noetic-visualization-msgs
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```
I have downloaded pykdl from its anaconda page: [https://anaconda.org/jf/pykdl](https://anaconda.org/jf/pykdl)
Then used `conda install ~/Downloads/pykdl-1.4.0.pybind11-py38_1.tar.bz2`
It shows it was installed and anaconda python still doesn't see it. 
```
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
```

`pip install pykdl` says the package doesn't exist

```
Collecting pykdl
  Using cached PyKDL-1.4.0.tar.gz (1.5 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/mr3albert/anaconda3/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-yyms9z4z/pykdl_8b1026bd22be46799ba5082b4126f8ff/setup.py'"'"'; __file__='"'"'/tmp/pip-install-yyms9z4z/pykdl_8b1026bd22be46799ba5082b4126f8ff/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-vefupkbi
         cwd: /tmp/pip-install-yyms9z4z/pykdl_8b1026bd22be46799ba5082b4126f8ff/
    Complete output (7 lines):
    running egg_info
    creating /tmp/pip-pip-egg-info-vefupkbi/PyKDL.egg-info
    writing /tmp/pip-pip-egg-info-vefupkbi/PyKDL.egg-info/PKG-INFO
    writing dependency_links to /tmp/pip-pip-egg-info-vefupkbi/PyKDL.egg-info/dependency_links.txt
    writing top-level names to /tmp/pip-pip-egg-info-vefupkbi/PyKDL.egg-info/top_level.txt
    writing manifest file '/tmp/pip-pip-egg-info-vefupkbi/PyKDL.egg-info/SOURCES.txt'
    error: package directory 'PyKDL' does not exist
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/48/1a/aa37dbcc769a54da4579ae1be049ddf445f6973455eadd05972163666219/PyKDL-1.4.0.tar.gz#sha256=a63eeb3f91d26e72cf369fa3f76d034f513f9d65d47d1de68fc3e783db6223d0 (from https://pypi.org/simple/pykdl/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement pykdl (from versions: 1.4.0)
ERROR: No matching distribution found for pykdl
```

**Comment by adnanmunawar** [comment]
Are you running the GUI controller example using `python3` or `python`?

**Comment by mr3albert** [comment]
I ended up figuring it out. The issue was I forgot to deactivate the conda environment to not use the conda python.
